version: '3.9'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./conf/:/etc/nginx/
      - ./includes/:/etc/nginx/includes/
    network_mode: bridge
