version: '3.9'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
      - ./data/includes/:/etc/nginx/includes/
    network_mode: bridge
